export const listatareas=[
    {
        taskName:'Tarea de prueba',
        taskComplete:false,
        taskEmployeeId:'ckz8lvea20002r4v2u3r7wpr9',
        taskModuleId:1,
    },
    {
        taskName:'Tarea de prueba',
        taskComplete:false,
        taskEmployeeId:'ckz8lvea20002r4v2u3r7wpr9',
        taskModuleId:2,
    },
    {
        taskName:'Tarea de prueba',
        taskComplete:false,
        taskEmployeeId:'ckz8lvea20002r4v2u3r7wpr9',
        taskModuleId:3,
    },
    {
        taskName:'Tarea de prueba',
        taskComplete:false,
        taskEmployeeId:'ckz8lvea20002r4v2u3r7wpr9',
        taskModuleId:4,
    },
    {
        taskName:'Tarea de prueba',
        taskComplete:false,
        taskEmployeeId:'ckz8lvea20002r4v2u3r7wpr9',
        taskModuleId:5,
    },
    {
        taskName:'Tarea de prueba',
        taskComplete:false,
        taskEmployeeId:'ckz8lvea20002r4v2u3r7wpr9',
        taskModuleId:6,
    },
    {
        taskName:'Tarea de prueba',
        taskComplete:false,
        taskEmployeeId:'ckz8lvea20002r4v2u3r7wpr9',
        taskModuleId:7,
    },
    {
        taskName:'Tarea de prueba',
        taskComplete:false,
        taskEmployeeId:'ckz8lvea20002r4v2u3r7wpr9',
        taskModuleId:8,
    },
    {
        taskName:'Tarea de prueba',
        taskComplete:false,
        taskEmployeeId:'ckz8lvea20002r4v2u3r7wpr9',
        taskModuleId:9,
    },
    {
        taskName:'Tarea de prueba 2',
        taskComplete:false,
        taskEmployeeId:'ckz8lvea20002r4v2u3r7wpr9',
        taskModuleId:1,
    },
    {
        taskName:'Tarea de prueba 2',
        taskComplete:false,
        taskEmployeeId:'ckz8lvea20002r4v2u3r7wpr9',
        taskModuleId:2,
    },
    {
        taskName:'Tarea de prueba 2',
        taskComplete:false,
        taskEmployeeId:'ckz8lvea20002r4v2u3r7wpr9',
        taskModuleId:3,
    },
    {
        taskName:'Tarea de prueba 2',
        taskComplete:false,
        taskEmployeeId:'ckz8lvea20002r4v2u3r7wpr9',
        taskModuleId:4,
    },
    {
        taskName:'Tarea de prueba 2',
        taskComplete:false,
        taskEmployeeId:'ckz8lvea20002r4v2u3r7wpr9',
        taskModuleId:5,
    },
    {
        taskName:'Tarea de prueba 2',
        taskComplete:false,
        taskEmployeeId:'ckz8lvea20002r4v2u3r7wpr9',
        taskModuleId:6,
    },
    {
        taskName:'Tarea de prueba 2',
        taskComplete:false,
        taskEmployeeId:'ckz8lvea20002r4v2u3r7wpr9',
        taskModuleId:7,
    },
    {
        taskName:'Tarea de prueba 2',
        taskComplete:false,
        taskEmployeeId:'ckz8lvea20002r4v2u3r7wpr9',
        taskModuleId:8,
    },
    {
        taskName:'Tarea de prueba 2',
        taskComplete:false,
        taskEmployeeId:'ckz8lvea20002r4v2u3r7wpr9',
        taskModuleId:9,
    },
]